version: 2
jobs:
  test:
    docker:
      - image: circleci/8.0-node-browsers-legacy

    steps:
      - checkout
      - run: composer install -n --prefer-dist
      - run: touch storage/testing.sqlite
      - run: php artisan migrate --env=testing --database=mysql --force
      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  workflow:
    jobs:
    - test