version: 2
jobs:
  test:
    docker:
      - image: circleci/php:8.0.3-zts-buster-node

    steps:
      - checkout
      - run: composer install -n --prefer-dist
      - run: php artisan key:generate
      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  workflow:
    jobs:
    - test